### ISSUE TITLE
error while executing

### ISSUE THREAD

**Issue by Junaidkhan1809** [Nkap23/background_removal_DL#1]
This code is not working in my local system, can you help me out with requirements of system and pre-requisite

**Comment by Nkap23** [comment]
Hello, on which step are you getting the error? Do you have all the required libraries installed?

**Comment by Junaidkhan1809** [comment]
While installing tensorflow, I am getting error, can you help me with installing tensorflow
I have ran the command pip install tensorflow
What all basic requirement are to install tensorflow hardware and software and python @Nkap23

**Comment by Junaidkhan1809** [comment]
![image](https://user-images.githubusercontent.com/72540582/109921832-773ef580-7ce2-11eb-8627-7149fec022c3.png)
